// <auto-generated />
using System;
using Egzamin.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Egzamin.Migrations
{
    [DbContext(typeof(MedicalDbContext))]
    partial class MedicalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Egzamin.Models.Doctor", b =>
                {
                    b.Property<int>("IdDoctor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDoctor");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            IdDoctor = 194343274,
                            Email = "aadamowicz@gmail.com",
                            FirstName = "Adam",
                            LastName = "Adamowicz"
                        },
                        new
                        {
                            IdDoctor = 765069155,
                            Email = "ffilipowicz@gmail.com",
                            FirstName = "Filip",
                            LastName = "Filipowicz"
                        },
                        new
                        {
                            IdDoctor = 1823315558,
                            Email = "jjanowicz@gmail.com",
                            FirstName = "Jan",
                            LastName = "Janowicz"
                        });
                });

            modelBuilder.Entity("Egzamin.Models.Medicament", b =>
                {
                    b.Property<int>("IdMedicament")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMedicament");

                    b.ToTable("Medicaments");

                    b.HasData(
                        new
                        {
                            IdMedicament = 70238570,
                            Description = "AA",
                            Name = "A",
                            Type = "AAA"
                        },
                        new
                        {
                            IdMedicament = 287846971,
                            Description = "AA",
                            Name = "A",
                            Type = "AAA"
                        },
                        new
                        {
                            IdMedicament = 1403662933,
                            Description = "AA",
                            Name = "A",
                            Type = "AAA"
                        });
                });

            modelBuilder.Entity("Egzamin.Models.Patient", b =>
                {
                    b.Property<int>("IdPatient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPatient");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            IdPatient = 126507981,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anna",
                            LastName = "Annawska"
                        },
                        new
                        {
                            IdPatient = 1514420107,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jadwiga",
                            LastName = "Jadwigowska"
                        },
                        new
                        {
                            IdPatient = 1047822992,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Justyna",
                            LastName = "Justynowska"
                        });
                });

            modelBuilder.Entity("Egzamin.Models.Prescription", b =>
                {
                    b.Property<int>("IdPrescription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDoctor")
                        .HasColumnType("int");

                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.HasKey("IdPrescription");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            IdPrescription = 794029451,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(1, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 194343274,
                            IdPatient = 126507981
                        },
                        new
                        {
                            IdPrescription = 1053208964,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(1, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 765069155,
                            IdPatient = 1514420107
                        },
                        new
                        {
                            IdPrescription = 360633305,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(1, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 1823315558,
                            IdPatient = 1047822992
                        });
                });

            modelBuilder.Entity("Egzamin.Models.Prescription_Medicament", b =>
                {
                    b.Property<int>("IdMedicament")
                        .HasColumnType("int");

                    b.Property<int>("IdPrescription")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Dose")
                        .HasColumnType("int");

                    b.HasKey("IdMedicament", "IdPrescription");

                    b.HasIndex("IdPrescription");

                    b.ToTable("Prescription_Medicaments");

                    b.HasData(
                        new
                        {
                            IdMedicament = 70238570,
                            IdPrescription = 794029451,
                            Details = "AAA",
                            Dose = 98
                        },
                        new
                        {
                            IdMedicament = 287846971,
                            IdPrescription = 1053208964,
                            Details = "AAA",
                            Dose = 72
                        },
                        new
                        {
                            IdMedicament = 1403662933,
                            IdPrescription = 360633305,
                            Details = "AAA",
                            Dose = 84
                        });
                });

            modelBuilder.Entity("Egzamin.Models.Prescription_Medicament", b =>
                {
                    b.HasOne("Egzamin.Models.Medicament", "medicament")
                        .WithMany()
                        .HasForeignKey("IdMedicament")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egzamin.Models.Prescription", "prescription")
                        .WithMany()
                        .HasForeignKey("IdPrescription")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("medicament");

                    b.Navigation("prescription");
                });
#pragma warning restore 612, 618
        }
    }
}
